import Foundation

/// Records a single prediction run with metadata for replay and diagnostics.
struct PredictionRecord: Identifiable, Sendable {
    let id: UUID
    let timestamp: Date
    /// The typed context that was sent to the model
    let typedContext: String
    /// The full continuation generated by the model
    let generatedContinuation: String
    /// Time to first token in seconds
    let timeToFirstToken: TimeInterval?
    /// Total prediction time in seconds
    let totalTime: TimeInterval
    /// How the prediction was resolved
    let resolution: PredictionResolution
    /// The model used
    let modelId: String
    /// The model display name at time of prediction
    let modelDisplayName: String
    /// The prediction mode at time of generation
    let mode: String
    /// Generation parameters used
    let parameters: PredictionParametersSnapshot
}

enum PredictionResolution: String, CaseIterable, Sendable {
    case accepted  // user accepted via Tab
    case ignored   // user typed over / past it
    case invalidated  // prediction became stale
    case cancelled // actively cancelled
    case rejected // engine confidence rejected
}

/// A snapshot of the generation parameters used for a prediction.
struct PredictionParametersSnapshot: Sendable {
    let verbosityBias: Double
    let continuationBias: Double
    let instructionStrictness: Double
    let maxWords: Int
    let temperature: Double
    let topP: Double
}

/// Thread-safe ring buffer of recent predictions for the replay UI.
@MainActor
final class PredictionHistory {
    private var records: [PredictionRecord] = []
    private let maxRecords: Int

    var allRecords: [PredictionRecord] {
        records
    }

    var latestRecord: PredictionRecord? {
        records.last
    }

    init(maxRecords: Int = 200) {
        self.maxRecords = maxRecords
    }

    func append(_ record: PredictionRecord) {
        records.append(record)
        if records.count > maxRecords {
            records.removeFirst(records.count - maxRecords)
        }
    }

    func clear() {
        records.removeAll()
    }

    /// Count of records matching a given resolution
    func count(resolution: PredictionResolution) -> Int {
        records.filter { $0.resolution == resolution }.count
    }

    /// Overall acceptance rate (accepted / total completed)
    var acceptanceRate: Double {
        let completed = records.filter { $0.resolution == .accepted || $0.resolution == .ignored }
        guard !completed.isEmpty else { return 0 }
        let accepted = completed.filter { $0.resolution == .accepted }.count
        return Double(accepted) / Double(completed.count)
    }

    /// Average total time for completed predictions
    var averageTotalTime: TimeInterval {
        let completed = records.filter { $0.resolution == .accepted || $0.resolution == .ignored }
        guard !completed.isEmpty else { return 0 }
        return completed.map(\.totalTime).reduce(0, +) / Double(completed.count)
    }

    /// Average time to first token for completed predictions
    var averageTimeToFirstToken: TimeInterval {
        let withTTFT = records.compactMap(\.timeToFirstToken)
        guard !withTTFT.isEmpty else { return 0 }
        return withTTFT.reduce(0, +) / Double(withTTFT.count)
    }
}